### ISSUE TITLE
Strange values from simpletest.py

### ISSUE THREAD

**Issue by danielcrisp** [adafruit/Adafruit_CircuitPython_AMG88xx#11]
I've just tried the simpletest.py example on my GridEye + R-Pi and I'm getting some very odd temperature readings:

```
['0.0', '0.0', '0.0', '511.2', '510.5', '510.8', '509.8', '506.5']

['1.5', '0.2', '511.5', '510.8', '510.0', '510.0', '509.8', '506.8']

['0.8', '0.0', '511.2', '510.8', '510.0', '509.8', '508.8', '506.2']

['511.8', '511.0', '510.8', '509.8', '510.2', '509.5', '508.8', '507.0']

['511.0', '510.8', '510.8', '510.2', '510.2', '509.2', '509.0', '506.0']

['510.8', '511.0', '510.8', '511.0', '510.2', '510.8', '509.5', '506.5']

['510.5', '510.8', '510.5', '511.0', '510.5', '509.8', '509.2', '505.0']

['508.8', '510.8', '511.2', '510.0', '511.8', '510.8', '509.0', '503.5']
```

It is unseasonably warm here but 500+°c seems a little excessive.

Update: The thermistor is reading 44.6

Any ideas?

**Comment by ladyada** [comment]
could be bad wiring or corrupted data! where did you buy the sensor?

**Comment by danielcrisp** [comment]
Just replicated on another GridEye / R-Pi.

```
Thermistor: 46.0
['511.0', '511.2', '511.8', '510.5', '509.5', '0.8', '0.0', '511.8']

['511.8', '511.5', '511.2', '511.2', '508.8', '1.2', '0.5', '511.2']

['511.8', '511.2', '511.5', '510.5', '508.5', '1.2', '0.0', '0.0']

['0.0', '0.2', '0.0', '511.2', '509.0', '1.0', '0.0', '1.5']

['0.0', '1.2', '0.5', '0.2', '509.0', '0.0', '511.2', '508.8']

['1.2', '0.5', '511.2', '511.8', '511.2', '511.5', '510.5', '508.5']

['1.2', '0.0', '0.0', '0.0', '0.2', '0.0', '511.2', '509.0']

['1.0', '0.0', '1.5', '0.0', '1.2', '0.5', '0.2', '509.0']
```

Not sure who they were bought from, but it was bought in bulk through work so I'm pretty sure they're genuine.

We've been seeing interference in some environments in the readings when reading using `smbus` (and doing other stuff) so I was hoping that your simple test would be cleaner and the problems could be isolated to our code pipeline. But this looks like something else is going on!

I read [here](https://raspi.tv/2013/rpi-gpio-basics-6-using-inputs-and-outputs-together-with-rpi-gpio-pull-ups-and-pull-downs) that GPIO wires can act as antenna and that enabling the pull-up / pull-down resistors can help. Does that sound feasible?

**Comment by ladyada** [comment]
if they're adafruit items - maybe post in the adafruit forums, also if you can test the breakout with an arduino that's a good idea!

**Comment by danielcrisp** [comment]
Ok, cool - I'll investigate. Thanks for the quick responses!

**Comment by robmarkcole** [comment]
@danielcrisp the grid-eye we are using does not have built in pull-up resistors, probably causing these odd readings

**Comment by dherrada** [comment]
@danielcrisp Were you ever able to get more accurate readings?

**Comment by danielcrisp** [comment]
@dherrada I didn't, no, but I didn't persevere either. Did you get it working ok @robmarkcole?

**Comment by danielcrisp** [comment]
I don't know what I was doing wrong before, but I've just tried this again and I'm getting decent results now.
