### ISSUE TITLE
MemoryError: memory allocation failed, allocating 768 bytes

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/Adafruit_CircuitPython_AMG88xx#13]
I am also intermittently hitting the following error:

```
>>> import adafruit_amg88xx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: memory allocation failed, allocating 768 bytes
```

Looks like https://github.com/adafruit/circuitpython/issues/569

**Comment by robmarkcole** [comment]
On occasions when I don't get the above error, I am then hitting:

```
>>> import adafruit_amg88xx
>>> amg = adafruit_amg88xx.AMG88XX(i2c_bus, addr=0x68) #Our devices are on 0x68
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'AMG88XX'
```

Is it possible the files are corrupted somehow? I have been doing a lot of rebooting of the device

**Comment by robmarkcole** [comment]
Another restart of the board and everything ran fine

**Comment by deshipu** [comment]
For the first one I would suspect unreliable connection of the wires or power issues. The second one does look like some kind of file system corruption or memory glitch.

**Comment by dherrada** [comment]
Have you had the issue since then?

**Comment by robmarkcole** [comment]
Not used it since

**Comment by dherrada** [comment]
@kattni Should I close this?

**Comment by kattni** [comment]
@dherrada Yes please!
