### ISSUE TITLE
Example needs renaming to match lib name

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_AMG88xx#18]
One example begins with `amg8xx_`. It should begin with `amg88x_` to match the lib name.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by makermelissa** [comment]
Shouldn't this actually be `amg88xx_`?

**Comment by kattni** [comment]
@makermelissa Yes. The PR is still open. I will have them fix it.
