### ISSUE TITLE
I/O Error when objects are closer than approximately 10cm

### ISSUE THREAD

**Issue by Reuspa** [adafruit/Adafruit_CircuitPython_AMG88xx#23]
Hello, 
i got 3 amg8833 running with a TCA9548A I2C Multiplexer. it works fine until something comes closer than 10cm in front off one off the Sensors, then i get a OSError: [Errno 121] Remote I/O error.
Any advice?

**Comment by caternuson** [comment]
Can you recreate the issue with a single AMG8833 (no multiplexer) running the example program?
https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx/blob/master/examples/amg88xx_simpletest.py

**Comment by Reuspa** [comment]
when I run the example program with a single AMG8833, I get one of two errors 1:OSError: [Errno 121] Remote I/O error  or 2: ValueError: No I2C device at address: 69. When I i2cdetect the i2cport changes. 
![Bildschirmfoto von 2020-01-14 11-44-41](https://user-images.githubusercontent.com/24221684/72338057-f2e77880-36c3-11ea-9ba3-eca5225bc7da.png)

this happens with all three sensors i got. Most post say its probably the wiring, but i change the wires multiple times  with new ones and i still get the same errors.

**Comment by ladyada** [comment]
yeah this is almost certainly something with the wiring

**Comment by caternuson** [comment]
Please post in the forums with photos of your setup:
https://forums.adafruit.com/

**Comment by Reuspa** [comment]
I am using new wires straight out of the box. I changed the raspberry I am using and still I get the same errors. 
but thank you guy for answering. I will post in forums.
