### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [adafruit/Adafruit_CircuitPython_AMG88xx#39]
Hi, In **Adafruit_CircuitPython_AMG88xx**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
Adafruit-Blinka
adafruit-circuitpython-register
adafruit-circuitpython-busdevice
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **Adafruit-Blinka** can be changed to *>=0.1.5,<=8.0.2*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the Adafruit-Blinka</summary>
 <pre>micropython.const
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>pygame.display.set_mode.fill
sphinx_rtd_theme.get_html_theme_path
float
pygame.init
enumerate
colour.Color.range_to
pygame.draw.rect
adafruit_register.i2c_bits.RWBits
time.sleep
bytearray
round
adafruit_amg88xx.AMG88XX
int
pygame.display.update
adafruit_bus_device.i2c_device.I2CDevice
datetime.datetime.now
constrain
busio.I2C
pygame.mouse.set_visible
math.floor
map_value
adafruit_register.i2c_bit.RWBit
sys.path.insert
_twos_comp_to_float
os.path.abspath
pygame.display.set_mode
min
i2c.write_then_readinto
range
os.environ.get
sys.stdout.write
max
colour.Color
scipy.interpolate.griddata
list
os.putenv
print_there
str
len
sys.stdout.flush
micropython.const
_signed_12bit_to_float
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by tekktrik** [comment]
I don't think a change like this makes sense for our project or needs.  Thanks for offering though!
